# Generated by Django 5.0.6 on 2024-06-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test10app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='act',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='incomplete',
            old_name='inc',
            new_name='incomplete',
        ),
        migrations.AlterModelTable(
            name='incomplete',
            table='incompletes',
        ),
    ]
