# Generated by Django 5.0.6 on 2024-06-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test10app', '0002_rename_act_activities_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='inc',
            new_name='incomplete',
        ),
    ]
