# Generated by Django 5.0.6 on 2024-06-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test10app', '0004_alter_incomplete_incomplete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='incomplete',
        ),
    ]
